### ISSUE TITLE
Bug Major: Search Bar Feature

### ISSUE THREAD

**Issue by wphan-1925132** [info442-su23/g-team#55]
Using Chrome on Windows

The search bar on the top right of the navigation bar does not work with any other page but the home page.  I expected to be able to search anything on the page that I'm on but any page other than the home page it shows me nothing after clicking search. It would be best to leave this only on the home page instead of in the navigation bar where it won't even work with other pages.
![image](https://github.com/info442-su23/g-team/assets/56050048/9db79982-a1dc-4ea3-8cd4-22a1ff9c5f39)

**Comment by jasmpa-1777547** [comment]
Decided to state it as: "bug minor". Search bar works only in the homepage because it's functionality is necessary only for searching posts but for nothing else. On the 'Friends List' page there is already a search feature to look up friends, so having another search bar in the navigation bar is not required. The search bar in the navigation bar will be removed from all pages instead and will only appear in the homepage.

**Comment by kchoi22** [comment]
Fixed the bug by displaying the search bar only in the homepage.
